In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('AWS Dataset/AWCustomers.csv')

In [3]:
df1.head()

CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN   
1       13249   NaN      Ryan        NaN     Perry    NaN   
2       29350   NaN     Julia        NaN  Thompson    NaN   
3       13503   NaN  Theodore        NaN     Gomez    NaN   
4       22803   NaN  Marshall          J      Shan    NaN   

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...   
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...   
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...   
3         2103 Baldwin Dr          NaN    Liverpool              England  ...   
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...   

         Education      Occupation Gender MaritalStatus HomeOwnerFlag  \
0        Bachelors        Clerical      M             M             1   
1  Partial College        Clerical      M             M             1   
2        Bachelors        Clerical      F             S             0   
3  Partial College  Skilled Manual      M             M             1   
4  Partial College  Skilled Manual      M             S             1   

  NumberCarsOwned NumberChildrenAtHome TotalChildren  YearlyIncome  \
0               3                    0             1         81916   
1               2                    1             2         81076   
2               3                    0             0         86387   
3               2                    1             2         61481   
4               1                    0             0         51804   

   LastUpdated  
0   2017-03-06  
1   2017-03-06  
2   2017-03-06  
3   2017-03-06  
4   2017-03-06  

[5 rows x 24 columns]

In [4]:
df2=pd.read_csv('AWS Dataset/AWSales.csv')

In [5]:
df2.head()

CustomerID  BikeBuyer  AvgMonthSpend
0       21173          1          50.97
1       13249          1          53.11
2       29350          1          54.08
3       13503          1          56.93
4       22803          1          55.41

In [6]:
df1=pd.concat([df1,df2['AvgMonthSpend']],axis=1)

In [7]:
df_final=pd.concat([df1,df2['BikeBuyer']],axis=1)

In [8]:
df_final.columns
df_final.drop(['CustomerID'],axis=1)

Title FirstName MiddleName  LastName Suffix            AddressLine1  \
0       NaN      Chad          C      Yuan    NaN      7090 C. Mount Hood   
1       NaN      Ryan        NaN     Perry    NaN     3651 Willow Lake Rd   
2       NaN     Julia        NaN  Thompson    NaN  1774 Tice Valley Blvd.   
3       NaN  Theodore        NaN     Gomez    NaN         2103 Baldwin Dr   
4       NaN  Marshall          J      Shan    NaN         Am Gallberg 234   
...     ...       ...        ...       ...    ...                     ...   
18356   NaN     Grace          C    Bailey    NaN      6627 Camelback Ct.   
18357   NaN     Tasha        NaN      Deng    NaN         9627 Kendall Rd   
18358   NaN    Jaclyn        NaN     Zhang    NaN       4364 Viera Avenue   
18359   NaN      Erin          I      Reed    NaN  3866 Mt. Everest Court   
18360   NaN    Amanda        NaN     Perry    NaN     7870 Orangewood Dr.   

      AddressLine2            City    StateProvinceName CountryRegionName  \
0              NaN      Wollongong      New South Wales         Australia   
1              NaN         Shawnee     British Columbia            Canada   
2              NaN     West Covina           California     United States   
3              NaN       Liverpool              England    United Kingdom   
4              NaN           Werne  Nordrhein-Westfalen           Germany   
...            ...             ...                  ...               ...   
18356          NaN        Coronado           California     United States   
18357          NaN  Port Macquarie      New South Wales         Australia   
18358          NaN       Beaverton               Oregon     United States   
18359          NaN       Vancouver     British Columbia            Canada   
18360          NaN       Grossmont           California     United States   

       ... Gender MaritalStatus HomeOwnerFlag NumberCarsOwned  \
0      ...      M             M             1               3   
1      ...      M             M             1               2   
2      ...      F             S             0               3   
3      ...      M             M             1               2   
4      ...      M             S             1               1   
...    ...    ...           ...           ...             ...   
18356  ...      F             M             0               1   
18357  ...      F             S             0               2   
18358  ...      F             S             0               2   
18359  ...      F             S             0               0   
18360  ...      F             M             1               2   

      NumberChildrenAtHome TotalChildren YearlyIncome  LastUpdated  \
0                        0             1        81916   2017-03-06   
1                        1             2        81076   2017-03-06   
2                        0             0        86387   2017-03-06   
3                        1             2        61481   2017-03-06   
4                        0             0        51804   2017-03-06   
...                    ...           ...          ...          ...   
18356                    0             2        52953   2017-03-06   
18357                    0             0        60992   2017-03-06   
18358                    0             0        51859   2017-03-06   
18359                    0             0        87177   2017-03-06   
18360                    0             0       136856   2017-03-06   

       AvgMonthSpend  BikeBuyer  
0              50.97        1.0  
1              53.11        1.0  
2              54.08        1.0  
3              56.93        1.0  
4              55.41        1.0  
...              ...        ...  
18356            NaN        NaN  
18357            NaN        NaN  
18358            NaN        NaN  
18359            NaN        NaN  
18360            NaN        NaN  

[18361 rows x 25 columns]

In [9]:
df_final=df_final[['City', 'Gender','HomeOwnerFlag','NumberCarsOwned','NumberChildrenAtHome',
                  'TotalChildren','YearlyIncome','AvgMonthSpend','BikeBuyer']]

In [10]:
df_final.head() #Gender ->label Encoding
                #city ->One Hot Encoding (Alot of cols therefore dropping it)
df_final=df_final.drop(['City'],axis=1)
df_final

Gender  HomeOwnerFlag  NumberCarsOwned  NumberChildrenAtHome  \
0          M              1                3                     0   
1          M              1                2                     1   
2          F              0                3                     0   
3          M              1                2                     1   
4          M              1                1                     0   
...      ...            ...              ...                   ...   
18356      F              0                1                     0   
18357      F              0                2                     0   
18358      F              0                2                     0   
18359      F              0                0                     0   
18360      F              1                2                     0   

       TotalChildren  YearlyIncome  AvgMonthSpend  BikeBuyer  
0                  1         81916          50.97        1.0  
1                  2         81076          53.11        1.0  
2                  0         86387          54.08        1.0  
3                  2         61481          56.93        1.0  
4                  0         51804          55.41        1.0  
...              ...           ...            ...        ...  
18356              2         52953            NaN        NaN  
18357              0         60992            NaN        NaN  
18358              0         51859            NaN        NaN  
18359              0         87177            NaN        NaN  
18360              0        136856            NaN        NaN  

[18361 rows x 8 columns]

In [11]:
#handling Null
print(df_final.isnull().sum())
#as we can see only 6 rows have null , we can remove them
df_final=df_final.dropna()

Gender                  0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
AvgMonthSpend           6
BikeBuyer               6
dtype: int64


In [12]:
print(df_final.isnull().sum())

Gender                  0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
AvgMonthSpend           0
BikeBuyer               0
dtype: int64


In [13]:
X=df_final.iloc[:,:-1].values
y=df_final.iloc[:,-1].values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0]= le.fit_transform(X[:,0])
print(X)

[[1 1 3 ... 1 81916 50.97]
 [1 1 2 ... 2 81076 53.11]
 [0 0 3 ... 0 86387 54.08]
 ...
 [0 0 0 ... 0 50961 49.56]
 [0 0 1 ... 0 33678 51.42]
 [0 1 0 ... 2 29758 52.27]]


In [14]:
#splitting the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [15]:
#scaling X_train and X_test(but with the same transforming values)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,5:7] = sc.fit_transform(X_train[:, 5:7])
X_test[:,5:7] = sc.transform(X_test[:, 5:7])

In [16]:
type(X_train)
from numpy.linalg import norm
A=X_train[0]
B=X_train[1]

In [17]:
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)

Cosine Similarity: -0.17355162802868124


In [18]:
#define Jaccard Similarity function
def jaccard(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection) / union

#find Jaccard Similarity between the two sets 
jaccard(A,B)


0.16666666666666666